/* ───────────────────────────────────────────────
   BlizzTherm · Catálogo de productos
   Datos maestros — edita solo este fichero
   ─────────────────────────────────────────────── */

const CATEGORIAS = [
  { id: "electricos",   nombre: "Calefactores Eléctricos",                   nombreEn: "Electric Heaters" },
  { id: "infrarrojos",  nombre: "Calefactores Infrarrojos",                  nombreEn: "Infrared Heaters" },
  { id: "gas",          nombre: "Cañones de Calor a Gas",                    nombreEn: "Gas Heat Cannons" },
  { id: "gasoil-dir",   nombre: "Cañones de Calor a Gasoil · Combustión Directa",  nombreEn: "Diesel Heat Cannons · Direct Combustion" },
  { id: "gasoil-ind",   nombre: "Cañones de Calor a Gasoil · Combustión Indirecta", nombreEn: "Diesel Heat Cannons · Indirect Combustion" },
];

const PRODUCTOS = [

  /* ═══════════════════════════════════════════════
     CALEFACTORES ELÉCTRICOS
     ═══════════════════════════════════════════════ */

  {
    id: "bte-50",
    categoria: "electricos",
    nombre: "Calefactor Eléctrico BTE 50",
    pvp: 86.00,
    imagen: "img/BTE-50.png",
    imagenes: ["img/BTE-50.png"],
    resumen: "Calefactor eléctrico portátil de 5 kW, monofásico. Ideal para talleres y zonas de trabajo pequeñas.",
    resumenEn: "5 kW portable electric heater, single-phase. Ideal for workshops and small work areas.",
    descripcion: "El BTE 50 es un calefactor industrial eléctrico portátil diseñado para calentar de forma rápida y localizada talleres, almacenes, obras y otras zonas de trabajo donde no se puede o no se quiere usar combustible. Dispone de 3 modos de funcionamiento: ventilación, 2,5 kW y 5 kW, seleccionables mediante mando frontal. Carcasa metálica con protección IP24.",
    descripcionEn: "The BTE 50 is a portable industrial electric heater designed for quick, localized heating of workshops, warehouses, construction sites and other work areas where fuel use is not possible or desired. It features 3 operating modes: ventilation, 2.5 kW and 5 kW, selectable via front dial. Metal casing with IP24 protection.",
    specs: [
      { label: "Potencia",           value: "2,5 / 5 kW" },
      { label: "Alimentación",       value: "Monofásico 400V/50Hz" },
      { label: "Intensidad",         value: "7,2 A" },
      { label: "Fusible",            value: "10 A" },
      { label: "Modos",              value: "Ventilación / 2,5 kW / 5 kW" },
      { label: "Termostato",         value: "Mecánico regulable" },
      { label: "Protección térmica",  value: "Rearme automático a 70°C" },
      { label: "Protección IP",       value: "IP24" },
      { label: "Eficiencia estacional", value: "85%" },
      { label: "Dimensiones",        value: "270 × 255 × 400 mm" },
      { label: "Peso",               value: "5,6 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "2.5 / 5 kW" },
      { label: "Supply",             value: "Single-phase 400V/50Hz" },
      { label: "Current",            value: "7.2 A" },
      { label: "Fuse",               value: "10 A" },
      { label: "Modes",              value: "Ventilation / 2.5 kW / 5 kW" },
      { label: "Thermostat",         value: "Adjustable mechanical" },
      { label: "Thermal protection", value: "Auto-reset at 70°C" },
      { label: "IP rating",          value: "IP24" },
      { label: "Seasonal efficiency",value: "85%" },
      { label: "Dimensions",         value: "270 × 255 × 400 mm" },
      { label: "Weight",             value: "5.6 kg" },
    ],
    aplicaciones: ["Talleres", "Almacenes", "Obras", "Zonas de trabajo sin combustible"],
    aplicacionesEn: ["Workshops", "Warehouses", "Construction sites", "Fuel-free work areas"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "bte-90",
    categoria: "electricos",
    nombre: "Calefactor Eléctrico BTE 90",
    pvp: 125.00,
    imagen: "img/BTE-90.png",
    imagenes: ["img/BTE-90.png"],
    resumen: "Calefactor eléctrico trifásico de 9 kW con 3 modos de funcionamiento.",
    resumenEn: "9 kW three-phase electric heater with 3 operating modes.",
    descripcion: "El BTE 90 es un calefactor industrial portátil con carcasa metálica diseñado para calentar de forma rápida y localizada talleres, naves industriales, almacenes, obras y otras zonas de trabajo que requieren calor puntual. Dispone de 3 modos: ventilación, 4,5 kW y 9 kW.",
    descripcionEn: "The BTE 90 is a portable industrial heater with metal casing designed for quick, localized heating of workshops, industrial buildings, warehouses, construction sites and other work areas requiring spot heat. It features 3 modes: ventilation, 4.5 kW and 9 kW.",
    specs: [
      { label: "Potencia",            value: "4,5 / 9 kW" },
      { label: "Alimentación",        value: "Trifásico 400V 3~" },
      { label: "Intensidad",          value: "13,0 A" },
      { label: "Conexión",            value: "Acoplador industrial 5 polos (380-415V)" },
      { label: "Modos",               value: "Ventilación / 4,5 kW / 9 kW" },
      { label: "Termostato",          value: "Mecánico regulable" },
      { label: "Protección térmica",   value: "Rearme manual (RESET) a 80°C" },
      { label: "Protección IP",        value: "IP24" },
      { label: "Eficiencia estacional",value: "85%" },
      { label: "Dimensiones",         value: "355 × 300 × 490 mm" },
      { label: "Peso",                value: "9,6 kg" },
    ],
    specsEn: [
      { label: "Power",               value: "4.5 / 9 kW" },
      { label: "Supply",              value: "Three-phase 400V 3~" },
      { label: "Current",             value: "13.0 A" },
      { label: "Connector",           value: "5-pole industrial coupler (380-415V)" },
      { label: "Modes",               value: "Ventilation / 4.5 kW / 9 kW" },
      { label: "Thermostat",          value: "Adjustable mechanical" },
      { label: "Thermal protection",  value: "Manual reset (RESET) at 80°C" },
      { label: "IP rating",           value: "IP24" },
      { label: "Seasonal efficiency", value: "85%" },
      { label: "Dimensions",          value: "355 × 300 × 490 mm" },
      { label: "Weight",              value: "9.6 kg" },
    ],
    aplicaciones: ["Talleres", "Naves industriales", "Almacenes", "Obras"],
    aplicacionesEn: ["Workshops", "Industrial buildings", "Warehouses", "Construction sites"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "bte-150",
    categoria: "electricos",
    nombre: "Calefactor Eléctrico BTE 150",
    pvp: 190.00,
    imagen: "img/BTE-150.png",
    imagenes: ["img/BTE-150.png"],
    resumen: "Calefactor eléctrico trifásico de 15 kW con 4 modos de funcionamiento para grandes superficies.",
    resumenEn: "15 kW three-phase electric heater with 4 operating modes for large areas.",
    descripcion: "El BTE 150 es un calefactor industrial portátil de alta potencia diseñado para calentar de forma rápida y eficaz naves industriales, talleres, almacenes, obras y otras zonas de trabajo de mayor superficie. Dispone de 4 modos de funcionamiento: ventilación, 5 kW, 10 kW y 15 kW, seleccionables mediante mando frontal.",
    descripcionEn: "The BTE 150 is a high-power portable industrial heater designed for quick and effective heating of large industrial buildings, workshops, warehouses, construction sites and other large work areas. It features 4 operating modes: ventilation, 5 kW, 10 kW and 15 kW, selectable via front dial.",
    specs: [
      { label: "Potencia",            value: "5 / 10 / 15 kW" },
      { label: "Alimentación",        value: "Trifásico 400V 3~" },
      { label: "Intensidad",          value: "21,7 A" },
      { label: "Conexión",            value: "Acoplador industrial 5 polos (380-415V)" },
      { label: "Modos",               value: "Ventilación / 5 kW / 10 kW / 15 kW" },
      { label: "Termostato",          value: "Mecánico regulable" },
      { label: "Protección térmica",   value: "Rearme manual (RESET) a 140°C" },
      { label: "Protección IP",        value: "IP24" },
      { label: "Eficiencia estacional",value: "85%" },
      { label: "Dimensiones",         value: "410 × 360 × 550 mm" },
      { label: "Peso",                value: "14,5 kg" },
    ],
    specsEn: [
      { label: "Power",               value: "5 / 10 / 15 kW" },
      { label: "Supply",              value: "Three-phase 400V 3~" },
      { label: "Current",             value: "21.7 A" },
      { label: "Connector",           value: "5-pole industrial coupler (380-415V)" },
      { label: "Modes",               value: "Ventilation / 5 kW / 10 kW / 15 kW" },
      { label: "Thermostat",          value: "Adjustable mechanical" },
      { label: "Thermal protection",  value: "Manual reset (RESET) at 140°C" },
      { label: "IP rating",           value: "IP24" },
      { label: "Seasonal efficiency", value: "85%" },
      { label: "Dimensions",          value: "410 × 360 × 550 mm" },
      { label: "Weight",              value: "14.5 kg" },
    ],
    aplicaciones: ["Naves industriales", "Talleres grandes", "Almacenes", "Obras"],
    aplicacionesEn: ["Industrial buildings", "Large workshops", "Warehouses", "Construction sites"],
    destacado: true,
    sageTools: null,
    gid: null,
  },

  {
    id: "bte-150r",
    categoria: "electricos",
    nombre: "Calefactor Eléctrico BTE 150R",
    pvp: 405.00,
    imagen: "img/BTE-150R.png",
    imagenes: ["img/BTE-150R.png"],
    resumen: "Calefactor eléctrico de 15 kW con ruedas para máxima movilidad en naves y talleres.",
    resumenEn: "15 kW electric heater on wheels for maximum mobility in industrial buildings and workshops.",
    descripcion: "El BTE 150R es la versión con ruedas del calefactor BTE 150, diseñado para ofrecer máxima movilidad en entornos industriales. Dispone de 3 niveles de potencia seleccionables (5, 10 y 15 kW) y mando frontal para selección de potencia. Incorpora ruedas y asas de transporte.",
    descripcionEn: "The BTE 150R is the wheeled version of the BTE 150, designed for maximum mobility in industrial environments. It features 3 selectable power levels (5, 10 and 15 kW) and a front dial for power selection. Includes wheels and transport handles.",
    specs: [
      { label: "Potencia",            value: "5 / 10 / 15 kW" },
      { label: "Alimentación",        value: "Trifásico 400V 3~" },
      { label: "Intensidad",          value: "21,7 A" },
      { label: "Conexión",            value: "Acoplador industrial 5 polos (380-415V)" },
      { label: "Modos",               value: "5 kW / 10 kW / 15 kW" },
      { label: "Termostato",          value: "Mecánico regulable" },
      { label: "Protección térmica",   value: "Limitador térmico" },
      { label: "Protección IP",        value: "IP24" },
      { label: "Eficiencia estacional",value: "85%" },
      { label: "Transporte",          value: "Ruedas + asas" },
      { label: "Dimensiones",         value: "322 × 600 × 555 mm" },
      { label: "Peso",                value: "17,9 kg" },
    ],
    specsEn: [
      { label: "Power",               value: "5 / 10 / 15 kW" },
      { label: "Supply",              value: "Three-phase 400V 3~" },
      { label: "Current",             value: "21.7 A" },
      { label: "Connector",           value: "5-pole industrial coupler (380-415V)" },
      { label: "Modes",               value: "5 kW / 10 kW / 15 kW" },
      { label: "Thermostat",          value: "Adjustable mechanical" },
      { label: "Thermal protection",  value: "Thermal limiter" },
      { label: "IP rating",           value: "IP24" },
      { label: "Seasonal efficiency", value: "85%" },
      { label: "Transport",           value: "Wheels + handles" },
      { label: "Dimensions",          value: "322 × 600 × 555 mm" },
      { label: "Weight",              value: "17.9 kg" },
    ],
    aplicaciones: ["Naves industriales", "Talleres", "Almacenes", "Obras"],
    aplicacionesEn: ["Industrial buildings", "Workshops", "Warehouses", "Construction sites"],
    destacado: true,
    sageTools: null,
    gid: null,
  },

  /* ═══════════════════════════════════════════════
     CALEFACTORES INFRARROJOS
     ═══════════════════════════════════════════════ */

  {
    id: "bti-20",
    categoria: "infrarrojos",
    nombre: "Calefactor Infrarrojos BTI 20",
    pvp: 510.00,
    imagen: "img/BTI-20.png",
    imagenes: ["img/BTI-20.png"],
    resumen: "Calefactor infrarrojo diésel de 20 kW. Calor radiante directo para exteriores y zonas muy ventiladas.",
    resumenEn: "20 kW diesel infrared heater. Direct radiant heat for outdoors and well-ventilated areas.",
    descripcion: "El BTI 20 es un calefactor industrial de infrarrojos alimentado por diésel/queroseno que proporciona calor radiante directo sin necesidad de mover aire. Con carcasa metálica y rejilla protectora frontal, incluye termostato integrado con display digital. Uso exclusivo en exteriores o zonas muy bien ventiladas.",
    descripcionEn: "The BTI 20 is a diesel/kerosene-powered industrial infrared heater that provides direct radiant heat without moving air. With metal casing and front protective grille, it includes an integrated thermostat with digital display. For exclusive outdoor or well-ventilated area use.",
    specs: [
      { label: "Potencia",           value: "20 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "1,6 kg/h" },
      { label: "Depósito",           value: "10,5 L" },
      { label: "Boquilla",           value: "0,4 GpH 60°S Danfoss" },
      { label: "Alimentación",       value: "220-240V/50Hz (110W)" },
      { label: "Termostato",         value: "Digital integrado" },
      { label: "Distancia seguridad",value: "Frontal: 2,5 m · Lateral/trasera: 1,5 m" },
      { label: "Dimensiones",        value: "Consultar ficha técnica" },
      { label: "Peso",               value: "18,2 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "20 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "1.6 kg/h" },
      { label: "Tank",               value: "10.5 L" },
      { label: "Nozzle",             value: "0.4 GpH 60°S Danfoss" },
      { label: "Supply",             value: "220-240V/50Hz (110W)" },
      { label: "Thermostat",         value: "Integrated digital" },
      { label: "Safety distance",    value: "Front: 2.5 m · Sides/rear: 1.5 m" },
      { label: "Dimensions",         value: "See technical datasheet" },
      { label: "Weight",             value: "18.2 kg" },
    ],
    aplicaciones: ["Obras", "Naves industriales", "Almacenes", "Zonas exteriores"],
    aplicacionesEn: ["Construction sites", "Industrial buildings", "Warehouses", "Outdoor areas"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "bti-45",
    categoria: "infrarrojos",
    nombre: "Calefactor Infrarrojos BTI 45",
    pvp: 965.00,
    imagen: "img/BTI-45.png",
    imagenes: ["img/BTI-45.png"],
    resumen: "Calefactor infrarrojo diésel de 40 kW con ruedas. Para grandes superficies exteriores.",
    resumenEn: "40 kW diesel infrared heater on wheels. For large outdoor surfaces.",
    descripcion: "El BTI 45 es un calefactor infrarrojo de alta potencia (40 kW) alimentado por diésel/queroseno, montado sobre bastidor con ruedas de transporte. Proporciona calor radiante directo sobre grandes superficies. Termostato integrado regulable (5-45°C) con display digital. Uso exclusivo en exteriores o zonas muy bien ventiladas.",
    descripcionEn: "The BTI 45 is a high-power (40 kW) diesel/kerosene infrared heater mounted on a frame with transport wheels. It provides direct radiant heat over large areas. Adjustable integrated thermostat (5-45°C) with digital display. For exclusive outdoor or well-ventilated area use.",
    specs: [
      { label: "Potencia",           value: "40 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "3,2 kg/h" },
      { label: "Depósito",           value: "38 L" },
      { label: "Alimentación",       value: "220-240V/50Hz (80W)" },
      { label: "Termostato",         value: "Digital regulable (5-45°C)" },
      { label: "Distancia seguridad",value: "Frontal: 5 m · Lateral/trasera: 1,5 m" },
      { label: "Transporte",         value: "Bastidor con ruedas" },
      { label: "Dimensiones",        value: "925 × 635 × 860 mm" },
      { label: "Peso",               value: "28,4 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "40 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "3.2 kg/h" },
      { label: "Tank",               value: "38 L" },
      { label: "Supply",             value: "220-240V/50Hz (80W)" },
      { label: "Thermostat",         value: "Adjustable digital (5-45°C)" },
      { label: "Safety distance",    value: "Front: 5 m · Sides/rear: 1.5 m" },
      { label: "Transport",          value: "Frame with wheels" },
      { label: "Dimensions",         value: "925 × 635 × 860 mm" },
      { label: "Weight",             value: "28.4 kg" },
    ],
    aplicaciones: ["Obras", "Naves abiertas", "Almacenes", "Muelles de carga"],
    aplicacionesEn: ["Construction sites", "Open buildings", "Warehouses", "Loading docks"],
    destacado: true,
    sageTools: null,
    gid: null,
  },

  {
    id: "btc-13",
    categoria: "infrarrojos",
    nombre: "Calefactor Infrarrojo BTC 13",
    pvp: 1190.00,
    imagen: "img/BTC-13.png",
    imagenes: ["img/BTC-13.png"],
    resumen: "Calefactor infrarrojo diésel de 13 kW con extracción de humos por chimenea. Para 70-90 m².",
    resumenEn: "13 kW diesel infrared heater with flue exhaust. Heats 70-90 m².",
    descripcion: "El BTC 13 es un calefactor infrarrojo de tubo radiante alimentado por diésel/queroseno con sistema de extracción de humos por chimenea (Ø75mm). Dispone de panel de control digital, termostato ambiente regulable, modo ECO con ciclos de 10/20/30 minutos, temporizador de apagado (1-24h) y bloqueo infantil. Requiere chimenea de acero inoxidable (máx. 4 m y 2 codos). Pensado para espacios de 70-90 m².",
    descripcionEn: "The BTC 13 is a radiant tube infrared heater powered by diesel/kerosene with a flue exhaust system (Ø75mm). It features a digital control panel, adjustable room thermostat, ECO mode with 10/20/30-minute cycles, shutdown timer (1-24h) and child lock. Requires stainless steel chimney (max. 4 m and 2 elbows). Designed for 70-90 m² spaces.",
    specs: [
      { label: "Potencia",           value: "13 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "1 kg/h" },
      { label: "Depósito",           value: "22 L" },
      { label: "Autonomía",          value: "~18 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (60W)" },
      { label: "Presión bomba",      value: "8 bar" },
      { label: "Eficiencia estacional",value: "84,3%" },
      { label: "Chimenea",           value: "Ø75 mm (máx. 4 m, 2 codos)" },
      { label: "Superficie",         value: "70-90 m²" },
      { label: "Termostato",         value: "Digital con modo ECO" },
      { label: "Dimensiones",        value: "820 × 430 × 1.008 mm" },
      { label: "Peso",               value: "41,3 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "13 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "1 kg/h" },
      { label: "Tank",               value: "22 L" },
      { label: "Autonomy",           value: "~18 hours" },
      { label: "Supply",             value: "220-240V/50Hz (60W)" },
      { label: "Pump pressure",      value: "8 bar" },
      { label: "Seasonal efficiency",value: "84.3%" },
      { label: "Chimney",            value: "Ø75 mm (max. 4 m, 2 elbows)" },
      { label: "Coverage",           value: "70-90 m²" },
      { label: "Thermostat",         value: "Digital with ECO mode" },
      { label: "Dimensions",         value: "820 × 430 × 1,008 mm" },
      { label: "Weight",             value: "41.3 kg" },
    ],
    aplicaciones: ["Talleres", "Naves de techo alto", "Muelles de carga", "Almacenes"],
    aplicacionesEn: ["Workshops", "High-ceiling buildings", "Loading docks", "Warehouses"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "btc-18",
    categoria: "infrarrojos",
    nombre: "Calefactor Infrarrojo BTC 18",
    pvp: 1375.00,
    imagen: "img/BTC-18.png",
    imagenes: ["img/BTC-18.png"],
    resumen: "Calefactor infrarrojo diésel de 18 kW con extracción de humos. Para espacios de 110-140 m².",
    resumenEn: "18 kW diesel infrared heater with flue exhaust. Heats 110-140 m².",
    descripcion: "El BTC 18 es el modelo de mayor potencia de la serie BTC, un calefactor infrarrojo de tubo radiante alimentado por diésel/queroseno con extracción de humos por chimenea (Ø75mm). Panel de control digital, termostato regulable, modo ECO (10/20/30 min), temporizador (1-24h), bloqueo infantil. Depósito de 60 L con autonomía de ~36 horas. Para espacios de 110-140 m².",
    descripcionEn: "The BTC 18 is the highest-power model in the BTC series, a radiant tube infrared heater powered by diesel/kerosene with flue exhaust (Ø75mm). Digital control panel, adjustable thermostat, ECO mode (10/20/30 min), timer (1-24h), child lock. 60 L tank with ~36 hours autonomy. For 110-140 m² spaces.",
    specs: [
      { label: "Potencia",           value: "18 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "1,42 kg/h" },
      { label: "Depósito",           value: "60 L" },
      { label: "Autonomía",          value: "~36 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (60W)" },
      { label: "Presión bomba",      value: "10 bar" },
      { label: "Eficiencia estacional",value: "84,5%" },
      { label: "Chimenea",           value: "Ø75 mm (máx. 4 m, 2 codos)" },
      { label: "Superficie",         value: "110-140 m²" },
      { label: "Termostato",         value: "Digital con modo ECO" },
      { label: "Dimensiones",        value: "1.305 × 435 × 1.120 mm" },
      { label: "Peso",               value: "62 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "18 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "1.42 kg/h" },
      { label: "Tank",               value: "60 L" },
      { label: "Autonomy",           value: "~36 hours" },
      { label: "Supply",             value: "220-240V/50Hz (60W)" },
      { label: "Pump pressure",      value: "10 bar" },
      { label: "Seasonal efficiency",value: "84.5%" },
      { label: "Chimney",            value: "Ø75 mm (max. 4 m, 2 elbows)" },
      { label: "Coverage",           value: "110-140 m²" },
      { label: "Thermostat",         value: "Digital with ECO mode" },
      { label: "Dimensions",         value: "1,305 × 435 × 1,120 mm" },
      { label: "Weight",             value: "62 kg" },
    ],
    aplicaciones: ["Naves de techo alto", "Talleres grandes", "Muelles de carga", "Almacenes"],
    aplicacionesEn: ["High-ceiling buildings", "Large workshops", "Loading docks", "Warehouses"],
    destacado: true,
    sageTools: null,
    gid: null,
  },

  /* ═══════════════════════════════════════════════
     CAÑONES DE CALOR A GAS
     ═══════════════════════════════════════════════ */

  {
    id: "btg-15",
    categoria: "gas",
    nombre: "Cañón de Calor a Gas BTG 15",
    pvp: 95.00,
    imagen: "img/BTG-15.png",
    imagenes: ["img/BTG-15.png"],
    resumen: "Cañón de calor a gas propano/butano de 15 kW. Portátil con encendido piezoeléctrico.",
    resumenEn: "15 kW propane/butane gas heat cannon. Portable with piezoelectric ignition.",
    descripcion: "El BTG 15 es un cañón de calor a gas propano/butano (GLP) diseñado para calentar de forma rápida y localizada. Dispone de encendido piezoeléctrico, inyector de 0,90 mm y protección contra sobrecalentamiento a 95°C. Asa de transporte integrada. Uso exclusivo en exteriores o zonas muy bien ventiladas. Bombona GLP no incluida.",
    descripcionEn: "The BTG 15 is a propane/butane (LPG) gas heat cannon designed for quick, localized heating. It features piezoelectric ignition, 0.90 mm injector and overheating protection at 95°C. Integrated transport handle. For exclusive outdoor or well-ventilated area use. LPG cylinder not included.",
    specs: [
      { label: "Potencia",           value: "15 kW (51.180 BTU)" },
      { label: "Combustible",        value: "GLP (propano/butano)" },
      { label: "Consumo",            value: "1,09 kg/h" },
      { label: "Presión gas",        value: "700 mbar" },
      { label: "Categoría gas",      value: "I3B/P" },
      { label: "Temp. salida aire",  value: "420°C" },
      { label: "Encendido",          value: "Piezoeléctrico" },
      { label: "Inyector",           value: "0,90 mm" },
      { label: "Alimentación",       value: "220-240V/50Hz (0,07 kW)" },
      { label: "Protección",         value: "Sobrecalentamiento 95°C" },
      { label: "Distancia seguridad",value: "Frontal: 3,5 m · Trasera: 2,5 m · Lateral: 2 m" },
      { label: "Transporte",         value: "Asa integrada" },
    ],
    specsEn: [
      { label: "Power",              value: "15 kW (51,180 BTU)" },
      { label: "Fuel",               value: "LPG (propane/butane)" },
      { label: "Consumption",        value: "1.09 kg/h" },
      { label: "Gas pressure",       value: "700 mbar" },
      { label: "Gas category",       value: "I3B/P" },
      { label: "Air outlet temp.",   value: "420°C" },
      { label: "Ignition",           value: "Piezoelectric" },
      { label: "Injector",           value: "0.90 mm" },
      { label: "Supply",             value: "220-240V/50Hz (0.07 kW)" },
      { label: "Protection",         value: "Overheat 95°C" },
      { label: "Safety distance",    value: "Front: 3.5 m · Rear: 2.5 m · Sides: 2 m" },
      { label: "Transport",          value: "Integrated handle" },
    ],
    aplicaciones: ["Obras", "Exteriores", "Zonas ventiladas", "Eventos"],
    aplicacionesEn: ["Construction sites", "Outdoors", "Ventilated areas", "Events"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "btg-30",
    categoria: "gas",
    nombre: "Cañón de Calor a Gas BTG 30",
    pvp: 159.00,
    imagen: "img/BTG-30.png",
    imagenes: ["img/BTG-30.png"],
    resumen: "Cañón de calor a gas de 30-50 kW con 2 etapas de potencia. Encendido piezoeléctrico.",
    resumenEn: "30-50 kW gas heat cannon with 2 power stages. Piezoelectric ignition.",
    descripcion: "El BTG 30 es un cañón de calor a gas propano/butano (GLP) de alto rendimiento con 2 etapas de potencia (30 a 50 kW). Dispone de encendido piezoeléctrico, inyector de 1,4 mm y protección contra sobrecalentamiento a 110°C. Asa de transporte integrada. Uso exclusivo en exteriores o zonas muy bien ventiladas. Bombona GLP no incluida.",
    descripcionEn: "The BTG 30 is a high-performance propane/butane (LPG) gas heat cannon with 2 power stages (30 to 50 kW). It features piezoelectric ignition, 1.4 mm injector and overheating protection at 110°C. Integrated transport handle. For exclusive outdoor or well-ventilated area use. LPG cylinder not included.",
    specs: [
      { label: "Potencia",           value: "30 – 50 kW (170.600 BTU)" },
      { label: "Combustible",        value: "GLP (propano/butano)" },
      { label: "Consumo",            value: "Hasta 3,63 kg/h" },
      { label: "Presión gas",        value: "1.500 mbar" },
      { label: "Categoría gas",      value: "I3B/P" },
      { label: "Temp. salida aire",  value: "360°C" },
      { label: "Encendido",          value: "Piezoeléctrico" },
      { label: "Inyector",           value: "1,4 mm" },
      { label: "Alimentación",       value: "220-240V/50Hz (0,07 kW)" },
      { label: "Protección",         value: "Sobrecalentamiento 110°C" },
      { label: "Distancia seguridad",value: "Frontal: 2,5 m · Trasera: 3,5 m · Lateral: 2 m" },
      { label: "Transporte",         value: "Asa integrada" },
    ],
    specsEn: [
      { label: "Power",              value: "30 – 50 kW (170,600 BTU)" },
      { label: "Fuel",               value: "LPG (propane/butane)" },
      { label: "Consumption",        value: "Up to 3.63 kg/h" },
      { label: "Gas pressure",       value: "1,500 mbar" },
      { label: "Gas category",       value: "I3B/P" },
      { label: "Air outlet temp.",   value: "360°C" },
      { label: "Ignition",           value: "Piezoelectric" },
      { label: "Injector",           value: "1.4 mm" },
      { label: "Supply",             value: "220-240V/50Hz (0.07 kW)" },
      { label: "Protection",         value: "Overheat 110°C" },
      { label: "Safety distance",    value: "Front: 2.5 m · Rear: 3.5 m · Sides: 2 m" },
      { label: "Transport",          value: "Integrated handle" },
    ],
    aplicaciones: ["Obras", "Naves abiertas", "Zonas ventiladas", "Eventos"],
    aplicacionesEn: ["Construction sites", "Open buildings", "Ventilated areas", "Events"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  /* ═══════════════════════════════════════════════
     CAÑONES DE CALOR A GASOIL · COMBUSTIÓN DIRECTA
     ═══════════════════════════════════════════════ */

  {
    id: "btd-20",
    categoria: "gasoil-dir",
    nombre: "Cañón de Calor Gasoil BTD 20",
    pvp: 275.00,
    imagen: "img/BTD-20.png",
    imagenes: ["img/BTD-20.png"],
    resumen: "Cañón de calor diésel de 20 kW, combustión directa. Portátil y compacto (10 kg).",
    resumenEn: "20 kW diesel heat cannon, direct combustion. Portable and compact (10 kg).",
    descripcion: "El BTD 20 es un cañón de calor diésel de combustión directa que proporciona 20 kW de potencia con un caudal de 550 m³/h. Portátil y compacto con solo 10 kg, incluye depósito de 12 L con autonomía de ~6 horas y termostato regulable. Uso exclusivo en exteriores o espacios muy bien ventilados.",
    descripcionEn: "The BTD 20 is a direct combustion diesel heat cannon delivering 20 kW with 550 m³/h airflow. Portable and compact at just 10 kg, it includes a 12 L tank with ~6 hours autonomy and adjustable thermostat. For exclusive outdoor or well-ventilated space use.",
    specs: [
      { label: "Potencia",           value: "20 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "1,65 kg/h" },
      { label: "Caudal de aire",     value: "550 m³/h" },
      { label: "Depósito",           value: "12 L" },
      { label: "Autonomía",          value: "~6 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (0,9 A)" },
      { label: "Termostato",         value: "Regulable" },
      { label: "Combustión",         value: "Directa" },
      { label: "Dimensiones",        value: "660 × 260 × 380 mm" },
      { label: "Peso",               value: "10 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "20 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "1.65 kg/h" },
      { label: "Airflow",            value: "550 m³/h" },
      { label: "Tank",               value: "12 L" },
      { label: "Autonomy",           value: "~6 hours" },
      { label: "Supply",             value: "220-240V/50Hz (0.9 A)" },
      { label: "Thermostat",         value: "Adjustable" },
      { label: "Combustion",         value: "Direct" },
      { label: "Dimensions",         value: "660 × 260 × 380 mm" },
      { label: "Weight",             value: "10 kg" },
    ],
    aplicaciones: ["Obras", "Exteriores", "Zonas ventiladas"],
    aplicacionesEn: ["Construction sites", "Outdoors", "Ventilated areas"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "btd-30",
    categoria: "gasoil-dir",
    nombre: "Cañón de Calor Gasoil BTD 30",
    pvp: 305.00,
    imagen: "img/BTD-30.png",
    imagenes: ["img/BTD-30.png"],
    resumen: "Cañón de calor diésel de 30 kW, combustión directa. Con ruedas y bastidor de transporte.",
    resumenEn: "30 kW diesel heat cannon, direct combustion. With wheels and transport frame.",
    descripcion: "El BTD 30 es un cañón de calor diésel de combustión directa de 30 kW con caudal de 720 m³/h. Incluye ruedas y bastidor de transporte, depósito de 19 L con autonomía de ~7 horas y termostato regulable. Ventilación permanente mínima de 750 cm² requerida.",
    descripcionEn: "The BTD 30 is a 30 kW direct combustion diesel heat cannon with 720 m³/h airflow. Includes wheels and transport frame, 19 L tank with ~7 hours autonomy and adjustable thermostat. Minimum 750 cm² permanent ventilation required.",
    specs: [
      { label: "Potencia",           value: "30 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "2,4 kg/h" },
      { label: "Caudal de aire",     value: "720 m³/h" },
      { label: "Depósito",           value: "19 L" },
      { label: "Autonomía",          value: "~7 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (1,1 A)" },
      { label: "Termostato",         value: "Regulable" },
      { label: "Ventilación",        value: "Mín. 750 cm² permanente" },
      { label: "Combustión",         value: "Directa" },
      { label: "Transporte",         value: "Ruedas + bastidor" },
      { label: "Dimensiones",        value: "830 × 410 × 540 mm" },
      { label: "Peso",               value: "18 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "30 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "2.4 kg/h" },
      { label: "Airflow",            value: "720 m³/h" },
      { label: "Tank",               value: "19 L" },
      { label: "Autonomy",           value: "~7 hours" },
      { label: "Supply",             value: "220-240V/50Hz (1.1 A)" },
      { label: "Thermostat",         value: "Adjustable" },
      { label: "Ventilation",        value: "Min. 750 cm² permanent" },
      { label: "Combustion",         value: "Direct" },
      { label: "Transport",          value: "Wheels + frame" },
      { label: "Dimensions",         value: "830 × 410 × 540 mm" },
      { label: "Weight",             value: "18 kg" },
    ],
    aplicaciones: ["Obras", "Naves abiertas", "Exteriores", "Zonas ventiladas"],
    aplicacionesEn: ["Construction sites", "Open buildings", "Outdoors", "Ventilated areas"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

  {
    id: "btd-50",
    categoria: "gasoil-dir",
    nombre: "Cañón de Calor Gasoil BTD 50",
    pvp: 369.00,
    imagen: "img/BTD-50.png",
    imagenes: ["img/BTD-50.png"],
    resumen: "Cañón de calor diésel de 51 kW, combustión directa. Alta potencia con depósito de 34 L.",
    resumenEn: "51 kW diesel heat cannon, direct combustion. High power with 34 L tank.",
    descripcion: "El BTD 50 es el modelo más potente de la serie BTD, un cañón de calor diésel de combustión directa de 51 kW con caudal de 750 m³/h. Incluye ruedas y bastidor de transporte, depósito de 34 L con autonomía de ~7 horas, termostato regulable con display digital. Ventilación permanente mínima de 750 cm² requerida.",
    descripcionEn: "The BTD 50 is the most powerful model in the BTD series, a 51 kW direct combustion diesel heat cannon with 750 m³/h airflow. Includes wheels and transport frame, 34 L tank with ~7 hours autonomy, adjustable thermostat with digital display. Minimum 750 cm² permanent ventilation required.",
    specs: [
      { label: "Potencia",           value: "51 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "4 kg/h" },
      { label: "Caudal de aire",     value: "750 m³/h" },
      { label: "Depósito",           value: "34 L" },
      { label: "Autonomía",          value: "~7 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (1,5 A)" },
      { label: "Termostato",         value: "Digital regulable" },
      { label: "Ventilación",        value: "Mín. 750 cm² permanente" },
      { label: "Combustión",         value: "Directa" },
      { label: "Transporte",         value: "Ruedas + bastidor" },
      { label: "Dimensiones",        value: "860 × 456 × 600 mm" },
      { label: "Peso",               value: "21,8 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "51 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "4 kg/h" },
      { label: "Airflow",            value: "750 m³/h" },
      { label: "Tank",               value: "34 L" },
      { label: "Autonomy",           value: "~7 hours" },
      { label: "Supply",             value: "220-240V/50Hz (1.5 A)" },
      { label: "Thermostat",         value: "Adjustable digital" },
      { label: "Ventilation",        value: "Min. 750 cm² permanent" },
      { label: "Combustion",         value: "Direct" },
      { label: "Transport",          value: "Wheels + frame" },
      { label: "Dimensions",         value: "860 × 456 × 600 mm" },
      { label: "Weight",             value: "21.8 kg" },
    ],
    aplicaciones: ["Obras grandes", "Naves industriales", "Exteriores", "Zonas ventiladas"],
    aplicacionesEn: ["Large construction sites", "Industrial buildings", "Outdoors", "Ventilated areas"],
    destacado: true,
    sageTools: null,
    gid: null,
  },

  /* ═══════════════════════════════════════════════
     CAÑONES DE CALOR A GASOIL · COMBUSTIÓN INDIRECTA
     ═══════════════════════════════════════════════ */

  {
    id: "bth-30",
    categoria: "gasoil-ind",
    nombre: "Cañón de Calor Gasoil BTH 30",
    pvp: 669.00,
    imagen: "img/BTH-30.png",
    imagenes: ["img/BTH-30.png"],
    resumen: "Cañón de calor diésel de 30 kW con combustión indirecta y extracción de humos. Aire limpio.",
    resumenEn: "30 kW diesel heat cannon with indirect combustion and flue exhaust. Clean air output.",
    descripcion: "El BTH 30 es un calefactor diésel de combustión indirecta con cámara de combustión cerrada y evacuación de gases por chimenea o conducto. Proporciona 30 kW de potencia con aire limpio (sin mezcla con gases de combustión), ideal para almacenes, invernaderos, obras cerradas o zonas que requieren aire limpio. Depósito de 50 L con autonomía de hasta 18 horas.",
    descripcionEn: "The BTH 30 is an indirect combustion diesel heater with closed combustion chamber and gas evacuation via chimney or duct. It delivers 30 kW with clean air output (no mixing with combustion gases), ideal for warehouses, greenhouses, sealed construction sites or areas requiring clean air. 50 L tank with up to 18 hours autonomy.",
    specs: [
      { label: "Potencia",           value: "30 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "2,4 kg/h" },
      { label: "Caudal de aire",     value: "780 m³/h" },
      { label: "Depósito",           value: "50 L" },
      { label: "Autonomía",          value: "Hasta 18 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (1,5 A / 250W)" },
      { label: "Presión bomba",      value: "10 bar" },
      { label: "Eficiencia estacional",value: "81,3%" },
      { label: "Combustión",         value: "Indirecta (cámara cerrada)" },
      { label: "Termostato",         value: "Integrado" },
      { label: "Dimensiones",        value: "1.110 × 490 × 750 mm" },
      { label: "Peso",               value: "34,4 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "30 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "2.4 kg/h" },
      { label: "Airflow",            value: "780 m³/h" },
      { label: "Tank",               value: "50 L" },
      { label: "Autonomy",           value: "Up to 18 hours" },
      { label: "Supply",             value: "220-240V/50Hz (1.5 A / 250W)" },
      { label: "Pump pressure",      value: "10 bar" },
      { label: "Seasonal efficiency",value: "81.3%" },
      { label: "Combustion",         value: "Indirect (closed chamber)" },
      { label: "Thermostat",         value: "Integrated" },
      { label: "Dimensions",         value: "1,110 × 490 × 750 mm" },
      { label: "Weight",             value: "34.4 kg" },
    ],
    aplicaciones: ["Almacenes cerrados", "Invernaderos", "Obras cerradas", "Zonas con aire limpio"],
    aplicacionesEn: ["Enclosed warehouses", "Greenhouses", "Sealed construction sites", "Clean air zones"],
    destacado: true,
    sageTools: null,
    gid: null,
  },

  {
    id: "bth-50",
    categoria: "gasoil-ind",
    nombre: "Cañón de Calor Gasoil BTH 50",
    pvp: 1035.00,
    imagen: "img/BTH-50.png",
    imagenes: ["img/BTH-50.png"],
    resumen: "Cañón de calor diésel de 51 kW con combustión indirecta. Máxima potencia con aire limpio.",
    resumenEn: "51 kW diesel heat cannon with indirect combustion. Maximum power with clean air.",
    descripcion: "El BTH 50 es el modelo de mayor potencia con combustión indirecta, proporcionando 51 kW de calor limpio sin gases en el ambiente. Cámara de combustión cerrada con evacuación de gases por conducto. Termostato integrado. Requiere instalación con conducto de evacuación y aporte de aire exterior adecuado.",
    descripcionEn: "The BTH 50 is the highest-power indirect combustion model, delivering 51 kW of clean heat without ambient gases. Closed combustion chamber with gas evacuation via duct. Integrated thermostat. Requires installation with evacuation duct and adequate external air intake.",
    specs: [
      { label: "Potencia",           value: "51 kW" },
      { label: "Combustible",        value: "Diésel / queroseno" },
      { label: "Consumo",            value: "4 kg/h" },
      { label: "Caudal de aire",     value: "750 m³/h" },
      { label: "Depósito",           value: "34 L" },
      { label: "Autonomía",          value: "~7 horas" },
      { label: "Alimentación",       value: "220-240V/50Hz (1,5 A / 340W)" },
      { label: "Presión aire",       value: "0,40 bar" },
      { label: "Fusible",            value: "T3.15A" },
      { label: "Eficiencia estacional",value: "81,3%" },
      { label: "Combustión",         value: "Indirecta (cámara cerrada)" },
      { label: "Termostato",         value: "Integrado" },
      { label: "Dimensiones",        value: "860 × 456 × 600 mm" },
      { label: "Peso",               value: "21,8 kg" },
    ],
    specsEn: [
      { label: "Power",              value: "51 kW" },
      { label: "Fuel",               value: "Diesel / kerosene" },
      { label: "Consumption",        value: "4 kg/h" },
      { label: "Airflow",            value: "750 m³/h" },
      { label: "Tank",               value: "34 L" },
      { label: "Autonomy",           value: "~7 hours" },
      { label: "Supply",             value: "220-240V/50Hz (1.5 A / 340W)" },
      { label: "Air pressure",       value: "0.40 bar" },
      { label: "Fuse",               value: "T3.15A" },
      { label: "Seasonal efficiency",value: "81.3%" },
      { label: "Combustion",         value: "Indirect (closed chamber)" },
      { label: "Thermostat",         value: "Integrated" },
      { label: "Dimensions",         value: "860 × 456 × 600 mm" },
      { label: "Weight",             value: "21.8 kg" },
    ],
    aplicaciones: ["Almacenes cerrados", "Invernaderos", "Obras selladas", "Industria alimentaria"],
    aplicacionesEn: ["Enclosed warehouses", "Greenhouses", "Sealed construction", "Food industry"],
    destacado: false,
    sageTools: null,
    gid: null,
  },

];
